import { resolve } from "path";
import { defineConfig } from "vite";
import dts from "vite-plugin-dts";
import solidPlugin from "vite-plugin-solid";

export default defineConfig({
	plugins: [
		solidPlugin(),
		dts({
			include: ["src"],
			outDir: "dist",
			entryRoot: "src",
		}),
	],
	build: {
		lib: {
			entry: {
				"publish/index": resolve(__dirname, "src/publish/index.tsx"),
				"watch/index": resolve(__dirname, "src/watch/index.tsx"),
				// Auto-generated by scripts/generate-wrappers.ts during prebuild phase
				"wrappers/react/index": resolve(__dirname, "src/wrappers/react/index.ts"),
			},
			formats: ["es"],
		},
		rollupOptions: {
			external: ["@moq/hang", "@moq/lite", "@moq/signals", "react"],
		},
		sourcemap: true,
		target: "esnext",
	},
});
